apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword }}
  GF_SMTP_PASSWORD: {{ .Values.grafana.smtpPassword }}

