namespace: monitoring

image:
  repository: prom/prometheus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

persistence:
  enabled: true
  size: 5Gi
  storageClass: "microk8s-hostpath"

prometheus:
  env:
    NARAD_QUEUE_USERNAME: "xxxxx"
    NARAD_QUEUE_PASSWORD: "xxxxx"
    NARAD_QUEUE_HOSTNAME: "xxxx"
    AGENTCIS_QUEUE_USERNAME: "xxxx"
    AGENTCIS_QUEUE_PASSWORD: "xxxxx"
    AGENTCIS_QUEUE_HOSTNAME: "xxxxx"
    AGENTCIS_V3_QUEUE_USERNAME: "xxxxx"
    AGENTCIS_V3_QUEUE_PASSWORD: "xxxxx"
    AGENTCIS_V3_QUEUE_HOSTNAME: "xxxxx"

  args:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    - '--web.enable-remote-write-receiver'
    - '--enable-feature=exemplar-storage'
    - '--storage.tsdb.retention.time=14d'
    - '--web.enable-admin-api'