# Microservice identifier
microserviceName: superadmin

# Namespace
namespace: agentcis-superadmin

managedBy: subash-chaudhary

# Image pull secrets
imagePullSecrets:
  - ecr-registry-secret

# Node affinity (shared by frontend and backend)
nodeAffinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - other-server
    - weight: 50
      preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - secondary-node1

# PVC names
pvc:
  config:
    name: nfs-superadmin-config-pvc
  log:
    name: nfs-superadmin-log-pvc

# PV configuration
pv:
  config:
    name: nfs-pv-superadmin-config
    capacity: 5Gi
    nfsPath: /agentcis-manifest/superadmin/config
    nfsServer: nfs.agentcisinteral.com
    reclaimPolicy: Retain
  log:
    name: nfs-pv-superadmin-log
    capacity: 5Gi
    nfsPath: /agentcis-pvc/helm-test
    nfsServer: nfs.agentcisinteral.com
    reclaimPolicy: Retain

# FRONTEND Configuration
frontend:
  enabled: true
  name: superadmin-frontend
  replicaCount: 1
  
  image:
    repository: 834033184010.dkr.ecr.ap-southeast-2.amazonaws.com/superadmin-frontend
    tag: superadmin-frontend-01-27-bbbc92d
    pullPolicy: IfNotPresent
  
  service:
    port: 80
    portName: nginx-http
    # type: ClusterIP
    targetPort: 80
    type: NodePort
    nodePort: 30008
  
  nginxConfigs:
  - mountPath: "/etc/nginx/conf.d/superadmin-frontend-nginx.conf"
    subPath: frontend-nginx.conf
  
  logs:
    mountPath: "/var/log/nginx"
    subPath: superadmin-frontend-log
  
  resources:
    requests:
      #cpu: "100m"
      memory: "200Mi"
    limits:
      #cpu: "250m"
      memory: "300Mi"
  
  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 80
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 120
        policies:
        - type: Pods
          value: 2
          periodSeconds: 30
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 60
  
  ingress:
    enabled: false
    host: smsfe.microservice.agentcis.com
    tlsSecretName: superadmin-frontend-tls-secret
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      nginx.ingress.kubernetes.io/rewrite-target: /

# BACKEND Configuration
backend:
  enabled: true
  name: superadmin-backend
  replicaCount: 1
  
  image:
    repository: 834033184010.dkr.ecr.ap-southeast-2.amazonaws.com/superadmin-backend
    tag: superadmin-backend-01-09-0879b87
    pullPolicy: IfNotPresent
  
  command: ["/bin/bash", "-c"]
  args:
    - |
      echo "-------------------------------"
      echo "k8s => starting php-fpm backend"
      echo "-------------------------------"
      php-fpm -D
      echo "-------------------------------"
      echo "k8s => restarting nginx"
      nginx -g "daemon off;"
  service:
    port: 80
    portName: backend-node-port
    # type: ClusterIP
    targetPort: 80
    type: NodePort
    nodePort: 30009

  envFile:
  - mountPath: "/superadmin/backend/.env"
    subPath: backend.env
  - mountPath: "/etc/nginx/conf.d/backend-nginx.conf"
    subPath: backend-nginx.conf
  - mountPath: "/etc/nginx/allow-list.conf"
    subPath: allow-list.conf
  - mountPath: "/superadmin/backend/storage/oauth-public.key"
    subPath: laravel_keys/oauth-public.key
  - mountPath: "/superadmin/backend/storage/oauth-private.key"
    subPath: laravel_keys/oauth-private.key 


  logs:
    mountPath: "/var/log/nginx"
    subPath: superadmin-backend-log
  
  resources:
    requests:
      # cpu: "250m"
      # memory: "400Mi"
      memory: "50Mi"
    limits:
      # cpu: "500m"    
      # memory: "600Mi"
      memory: "50Mi"
  
  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 120
        policies:
        - type: Pods
          value: 1
          periodSeconds: 30
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 60
  
  ingress:
    enabled: false
    host: smsapi.microservice.agentcis.com
    tlsSecretName: superadmin-backend-tls-secret
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt
      nginx.ingress.kubernetes.io/proxy-intercept-errors: "false"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"


backendConsumer:
  enabled: false

auth:
  enabled: false
